### Register

POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "123"
}

### Login

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "123"
}

### Check auth

POST http://localhost:3000/checkAuth HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY2MTk5MjMxYmVmZWJlMjE0YWQzYzc4NSIsImxvZ2dlZEF0IjoxNzEzNzI4NDU3MDI3LCJpYXQiOjE3MTM3Mjg0NTcsImV4cCI6MTcxMzczNTY1N30.2eoeiv9ibhVvD2pvIEAQtt28mjN9OsEaMF5XK64Dfq8
